### ISSUE TITLE
Positions API request failed "due to inactive_instruments"

### ISSUE THREAD

**Issue by samdavidson** [rghuckins/robinhood-google-sheets#11]
Hey, first off -- this is such a cool tool. I'm loving playing around here. Thank you so much for sharing @rghuckins !

I have a stock in my purchase history that is no longer active (TECS), so when I run "=ROBINHOOD_GET_POSITIONS()" I get the following error:

**"Robinhood API request failed. 400: {"inactive_instruments":["TECS"]} (line 90)."**

Screenshot: https://puu.sh/FBiad/83d12a0119.png

Is there anyway to edit the script, to have it exclude _inactive_instruments_? Big thanks in advance.

- Sam

**Comment by philgapp** [comment]
Hi Sam, I'm actively working with this in a project of mine and will take a quick look for you! May I ask what you're using it for?!

Phillip

**Comment by philgapp** [comment]
It appears that would have to be excluded on the Robinhood side, that error is coming from from their API and I don't see any place or way of easily (or at all) excluding that detail when making the API request :( The really sad thing is it isn't a public API and I don't know but assume they wouldn't help us figure it out.

**Comment by samdavidson** [comment]
Yeah, no worries. Thanks a ton for taking a look @philgapp !

Still really enjoying the options portion. I'm just trying to be a bit more analytical with those and see if there's a way to trade a bit smarter by looking at volume data or potentially things like _low_fill_rate_buy_price_, for example. Regardless it's a much better way to view your options portfolio, the greeks, how you're doing, what to consider selling, etc.

**Comment by philgapp** [comment]
My pleasure!

That sounds awesome! My app is focused more on general stocks, I want a better window into my current, watchlist and historical data centered mostly on long term dividends with a side of 'daytrading' to 1 year trades. I'm also building in a lot of the math to give me all the price targets (buy, sell, sell 2, and stop) and help alert me when rebalancing could reduce risk / increase return (i.e. div cuts, overvalued positions, etc.). In the end I want it to be an education tool as well, so new investors can more quickly grasp the basics and understand the key 'laws' to intelligent investing as they start to identify and enter positions. 

Perhaps someday we could join forces and end up with something that has both pieces, because I'm new to options myself :) When the prototype is done I want to have a free base version and then offer very inexpensive upgrades on Patreon. Maybe it will generate some passive income, maybe not!

**Comment by samdavidson** [comment]
@philgapp sounds really cool. I think there's a ton of demand for a RH supplement with more data, tools, etc. A lot of people are trying to cobble a few tools together with RH, like Koyfin, Yahoo Finance. But most of them don't have any RH integration (Yahoo does but I don't trust them), which is a major pain point and prevents stickiness.

Let me know if you need beta testers! samwdavidson at gmail

**Comment by samdavidson** [comment]
hey @philgapp not sure if you saw, but this was solved in a previous thread that I missed - https://github.com/rghuckins/robinhood-google-sheets/issues/3#issuecomment-470720584

**Comment by philgapp** [comment]
> hey @philgapp not sure if you saw, but this was solved in a previous thread that I missed - [#3 (comment)](https://github.com/rghuckins/robinhood-google-sheets/issues/3#issuecomment-470720584)

Thanks Sam! 

I love/hate to say it, but my application evolved quickly from my pre-prototype in Google Sheets/Scripts to a Node.js/React/Next app connected to the Alpaca API https://alpaca.markets/ (both for data and automated, algorithmic-based, commission-free trading with a very similar model to RobinHood). They offer a paper trading account for free which is really cool, Polygon market data with a funded live account, and the only downside is they don't support options yet (but coming soon). They do support shorting.

I'd still like to connect it to Robinhood, but without better documentation of their API that is troublesome for me as well.

Wouldn't have made it this far without this repo - and lots of respect to everyone working on / finding / using it!! I will continue to follow :)
